-- PHÂN QUYỀN --
-- Tạo Role cho Quản Lý
CREATE ROLE 'VaiTro_QuanLy';

-- Tạo Role cho Nhân Viên
CREATE ROLE 'VaiTro_NhanVien';

-- Tạo Role cho Cư Dân 
CREATE ROLE 'VaiTro_CuDan';

-- Tạo Người dùng Quản lý và gán role
CREATE USER 'NguoiDung_QuanLy' @'localhost' IDENTIFIED BY 'QuanLy';
GRANT 'VaiTro_QuanLy' TO 'NguoiDung_QuanLy'@'localhost';
SET DEFAULT ROLE 'VaiTro_QuanLy' TO 'NguoiDung_QuanLy'@'localhost';

-- Tạo Người dùng Nhân viên và gán role
CREATE USER 'NguoiDung_NhanVien' @'localhost' IDENTIFIED BY 'NhanVien';
GRANT 'VaiTro_NhanVien' TO 'NguoiDung_NhanVien'@'localhost';
SET DEFAULT ROLE 'VaiTro_NhanVien' TO 'NguoiDung_NhanVien'@'localhost';

-- Tạo Người dùng Cư dân và gán Role
CREATE USER 'NguoiDung_CuDan' @'localhost' IDENTIFIED BY 'CuDan';
GRANT 'VaiTro_CuDan' TO 'NguoiDung_CuDan'@'localhost';
SET DEFAULT ROLE 'VaiTro_CuDan' TO 'NguoiDung_CuDan'@'localhost';

-- Gán bảng cho Quản lý
GRANT SELECT(MaNV, TenNV, GioiTinh, SDT, DiaChi, NgSinh, NgVL, LoaiNV), INSERT, UPDATE(MaNV, TenNV, GioiTinh, SDT, DiaChi, NgSinh, NgVL, LoaiNV) ON QLCHUNGCU.NhanVien TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLCHUNGCU.DichVu TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE ON QLCHUNGCU.HoaDon TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT SELECT(MaCD, TenCD, GioiTinh, SDT, NgSinh, QueQuan, MaCH, NgVaoO) ON QLCHUNGCU.CuDan TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLCHUNGCU.ThongBao TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE ON QLCHUNGCU.CanHo TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLCHUNGCU.ThietBi TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE ON QLCHUNGCU.Tang TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE ON QLCHUNGCU.Toa TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE ON QLCHUNGCU.PhanAnh TO VaiTro_QuanLy WITH GRANT OPTION;

-- Gán Stored procedures cho Quản lý
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DS_Cudan TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DSHoadon_CanHo TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DSCuDan_CanHo TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DSNV_XuLyDV_Ngay TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DSNV_LoaiNV TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DSCanHo_ChuaThanhToanHD TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_CapNhatTT_CanHo TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_TimThongBao_Ngay TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_TTCuDan_MaCD TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.GuiThongBaoChoCanHo TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.GuiThongBaoChoTatCaCanHo TO VaiTro_QuanLy WITH GRANT OPTION;

-- Gán Functions cho Quản lý
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_SoCanHo TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_SoPhongTrong TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_SLCuDan_Toa TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_SLCuDan TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_TongChiPhi_CanHo TO VaiTro_QuanLy WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_TongHDChuaTT_CuDan TO VaiTro_QuanLy WITH GRANT OPTION;

-- Gán bảng cho Nhân Viên
GRANT SELECT(MaNV, TenNV, GioiTinh, SDT, DiaChi, NgSinh, NgVL, LoaiNV), UPDATE(MaNV, TenNV, GioiTinh, SDT, DiaChi, NgSinh, NgVL, LoaiNV) ON QLCHUNGCU.NhanVien TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLCHUNGCU.DichVu TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE ON QLCHUNGCU.HoaDon TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT SELECT(MaCD, TenCD, GioiTinh, SDT, NgSinh, QueQuan, MaCH, NgVaoO) ON QLCHUNGCU.CuDan TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLCHUNGCU.ThongBao TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE ON QLCHUNGCU.CanHo TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLCHUNGCU.ThietBi TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE ON QLCHUNGCU.Tang TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE ON QLCHUNGCU.Toa TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE ON QLCHUNGCU.PhanAnh TO VaiTro_NhanVien WITH GRANT OPTION;

-- Gán Stored procedures cho Nhân Viên
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DS_Cudan TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DSHoadon_CanHo TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DSCuDan_CanHo TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DSNV_XuLyDV_Ngay TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DSNV_LoaiNV TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_DSCanHo_ChuaThanhToanHD TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_CapNhatTT_CanHo TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_TimThongBao_Ngay TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_TTCuDan_MaCD TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_GuiThongBaoChoCanHo TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_GuiThongBaoChoTatCaCanHo TO VaiTro_NhanVien WITH GRANT OPTION;

-- Gán Functions cho Nhân Viên
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_SoCanHo TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_SoPhongTrong TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_SLCuDan_Toa TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_SLCuDan TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_TongChiPhi_CanHo TO VaiTro_NhanVien WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION QLCHUNGCU.FT_TongHDChuaTT_CuDan TO VaiTro_NhanVien WITH GRANT OPTION;

-- Gán bảng cho Cư Dân
GRANT SELECT ON QLCHUNGCU.DichVu TO VaiTro_CuDan WITH GRANT OPTION;
GRANT SELECT ON QLCHUNGCU.HoaDon TO VaiTro_CuDan WITH GRANT OPTION;
GRANT SELECT, UPDATE ON QLCHUNGCU.CuDan TO VaiTro_CuDan WITH GRANT OPTION;
GRANT SELECT ON QLCHUNGCU.ThongBao TO VaiTro_CuDan WITH GRANT OPTION;
GRANT SELECT ON QLCHUNGCU.CanHo TO VaiTro_CuDan WITH GRANT OPTION;
GRANT SELECT ON QLCHUNGCU.ThietBi TO VaiTro_CuDan WITH GRANT OPTION;
GRANT SELECT ON QLCHUNGCU.Tang TO VaiTro_CuDan WITH GRANT OPTION;
GRANT SELECT ON QLCHUNGCU.Toa TO VaiTro_CuDan WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLCHUNGCU.PhanAnh TO VaiTro_CuDan WITH GRANT OPTION;

-- Gán Stored Procedures cho Cư Dân
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_TimThongBao_Ngay TO VaiTro_CuDan WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_In_TTCuDan_MaCD TO VaiTro_CuDan WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE QLCHUNGCU.SP_CapNhatTT_CanHo TO VaiTro_CuDan WITH GRANT OPTION;
